name: Website Scanner

on:
  push:
    branches:
      - main

jobs:
  scan-website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Run Dastardly Action Step
        continue-on-error: true                        # This allows subsequent steps to run even if this step fails
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: ${{ secrets.URL_FROM_JAVA_APP }}
          env:
          YOUR_API_KEY: ${{ secrets.YOUR_API_KEY }}
    
      # You can replace this next step with any JUnit XML parser of your choosing
      - name: Publish Test Report
        if: always()                                   
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/dastardly-report.xml'       
          require_tests: true

     
